export const ARCSWEEP_OS_VERSION = '0.1.0-rc.7';
export const ARCSWEEP_OS_SCHEMA = 'arcsweep.os-manifest/v1';

export const ARCSWEEP_OS_MANIFEST = Object.freeze({
  schema: ARCSWEEP_OS_SCHEMA,
  version: ARCSWEEP_OS_VERSION,
  stage: 'runnable-release-candidate-ontological-kernel',
  authority: Object.freeze({
    modelRuntime: 'house-runtime+cognitive-edge',
    browserState: 'hearthfire',
    orchestration: 'arcsweep-os-kernel',
    stewardship: 'human-steward',
  }),
  repair: Object.freeze({
    maximumAutomaticAttemptsPerFault: 1,
    maximumAutomaticRepairsPerService: 3,
    sourceCodeMutation: 'pr-mediated',
    rollbackRequired: true,
  }),
  governance: Object.freeze({
    weightedAdvisoryInput: true,
    dissentPreserved: true,
    weightedSignalGrantsAuthority: false,
    securityEvidenceGrantsAuthority: false,
    stewardReviewForGovernanceChange: true,
    privilegedApprovalRequiresTrustedHumanAction: true,
    learningPromotionRequiresHumanStewardAction: true,
    modelMaySelfPromoteLearning: false,
    durableAbstractionRequiresLossReceipt: true,
    similarityImpliesIdentity: false,
    ontologyReviewRequiresHumanStewardAction: true,
  }),
  security: Object.freeze({
    capabilityFirewall: true,
    failClosedPolicyEvaluation: true,
    featherBlocksNonReadCapabilities: true,
    forgedStewardClaimsDenied: true,
    criticalRiskMutationPolicy: 'deny-until-steward-review',
    privilegedAuthority: 'scoped-short-lived-steward-lease',
    authorityLeaseTokensExposedInDiagnostics: false,
    diagnosticsPayloadsRedacted: true,
    modelSelfApproval: false,
    autonomousOffensiveAction: false,
  }),
  runtime: Object.freeze({
    bootLifecycle: ['BOOTING', 'READY', 'DEGRADED', 'PAUSED', 'ERROR'],
    guideDirectOrganAccess: false,
    guideMaximumCapabilityRequestsPerTurn: 1,
    guidePreferredRuntime: 'supabase-edge-to-openrouter',
    guideFallbackRuntime: 'constellation-runtime',
    guideRecentConversation: true,
    guideRecentConversationLimit: 10,
    cognitiveLearning: true,
    cognitiveLearningMode: 'observe-then-steward-promote',
    durableWorkspaceContext: true,
    passiveDeviceProving: true,
    temporalWitness: true,
    temporalWitnessStorage: 'browser-local-only',
    temporalWitnessLens: true,
    temporalConvergenceSignal: true,
    guideTemporalAccess: 'summary-and-headers-only',
    timeRoom: true,
    timeRoomSurface: true,
    universeTimeRegistry: true,
    universeStateTime: true,
    guideTimeRoomAccess: 'bounded-read-only',
    ontologicalKernel: true,
    ontologyObserverSync: true,
    ontologyTransformationReceipts: true,
    ontologyReview: 'steward-scored-five-axis-loss-review',
  }),
  contracts: Object.freeze({
    contextCapsule: 'arcsweep.context-capsule/v1',
    contextState: 'arcsweep.os-context-state/v1',
    workspaceContext: 'arcsweep.workspace-context/v1',
    eventReceipt: 'arcsweep.os-event-receipt/v1',
    observerTimeline: 'arcsweep.observer-os-timeline/v1',
    temporalWitnessLedger: 'arcsweep.temporal-witness-ledger/v1',
    temporalRecord: 'arcsweep.temporal-record/v1',
    temporalRecordHeader: 'arcsweep.temporal-record-header/v1',
    temporalWitnessSummary: 'arcsweep.temporal-witness-summary/v1',
    temporalWitnessEvent: 'arcsweep.temporal-witness-event/v1',
    timeRoomStatus: 'arcsweep.time-room-status/v1',
    timeRoomSnapshot: 'arcsweep.time-room-snapshot/v1',
    timeRoomClock: 'arcsweep.time-room-clock/v1',
    timeRoomEvent: 'arcsweep.time-room-event/v1',
    universeTimeProfile: 'arcsweep.universe-time-profile/v1',
    universeTimeRegistry: 'arcsweep.time-room-universe-registry/v1',
    health: 'arcsweep.service-health/v1',
    repairReceipt: 'arcsweep.repair-receipt/v1',
    checkpoint: 'arcsweep.checkpoint/v1',
    diagnostics: 'arcsweep.os-diagnostics/v1',
    bootState: 'arcsweep.os-boot-state/v1',
    service: 'arcsweep.os-service/v1',
    capability: 'arcsweep.os-capability/v1',
    capabilityReceipt: 'arcsweep.os-capability-receipt/v1',
    authorityLease: 'arcsweep.authority-lease/v1',
    securityTripwire: 'arcsweep.security-tripwire/v1',
    stewardApproval: 'arcsweep.steward-approval/v1',
    stewardDeliberation: 'arcsweep.steward-deliberation/v1',
    guideTurn: 'arcsweep.guide-turn/v1',
    cognitiveRuntime: 'arcsweep.cognitive-runtime/v1',
    cognitiveModelResponse: 'arcsweep.cognitive-model-response/v1',
    learningObservation: 'arcsweep.learning-observation/v1',
    learningFeedback: 'arcsweep.learning-feedback/v1',
    ontologyRuntime: 'arcsweep.ontology-runtime/v1',
    ontologyClaim: 'arcsweep.ontology-claim/v1',
    ontologyTransformation: 'arcsweep.ontology-transformation/v1',
    ontologyReview: 'arcsweep.ontology-review/v1',
    glyphForgeStatus: 'arcsweep.glyphforge-status/v1',
    runaStatus: 'arcsweep.runa-status/v1',
    deviceStatus: 'arcsweep.device-status/v1',
    deviceInputProof: 'arcsweep.device-input-proof/v1',
    cybersecurityIntelligence: 'arcsweep.cybersecurity-intelligence/v1',
    cybersecuritySeed: 'arcsweep.cybersecurity-seed/v1',
  }),
});
