import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { CORE_CAPABILITIES, PLUGIN_MANIFESTS, SITE_CONSTELLATION, buildPluginEvent } from './pluginRegistry.js';
import { localPathToAlias } from './artifactContract.js';
import './styles.css';

const DEFAULT_DEEP_VECTOR = { P: 0.55, C: 0.55, R: 0.45, E: 0.377, M: 0.0, A: 0.654, Q: 0.55 };
const DEFAULT_BINDINGS = [
  { key: 'terra_root', label: 'Terra Aeterna Root', path: '', scope: 'local-only' },
  { key: 'observer_logs', label: 'Observer Logs', path: '', scope: 'bridge-ready' },
  { key: 'artifacts', label: 'Artifacts', path: '', scope: 'bridge-ready' },
  { key: 'music_tones', label: 'Music / Tones', path: '', scope: 'bridge-ready' },
  { key: 'images_sigils', label: 'Images / Sigils', path: '', scope: 'bridge-ready' },
  { key: 'writer_drafts', label: 'Writer Room Drafts', path: '', scope: 'local-only' },
];

function clamp01(value) { const n = Number(value); return Number.isFinite(n) ? Math.max(0, Math.min(1, n)) : 0; }
function buildBridgeEvent({ title, kind, direction, motifs, deepVector, selectedBinding, pluginId }) { return { bridge_owner: 'flameclyffe', integration_target: 'nocturne-project-zero', plugin_id: pluginId, kind, direction, title: title || 'Untitled Companion bridge event', local_binding_key: selectedBinding?.key || null, local_path_alias: localPathToAlias(selectedBinding?.path || ''), raw_local_path_persisted: false, motifs: motifs.split(',').map((item) => item.trim()).filter(Boolean), deep_vector: deepVector, visibility: selectedBinding?.scope || 'local-only', created_at: new Date().toISOString(), rule: 'Data sets atmosphere, not fate.' }; }

function App() {
  const [bindings, setBindings] = useState(DEFAULT_BINDINGS); const [selectedKey, setSelectedKey] = useState(DEFAULT_BINDINGS[0].key); const [selectedPluginId, setSelectedPluginId] = useState(PLUGIN_MANIFESTS[0].id);
  const [title, setTitle] = useState('Arcsweep constellation receipt'); const [kind, setKind] = useState('constellation_socket'); const [direction, setDirection] = useState('bidirectional'); const [motifs, setMotifs] = useState('arcsweep, glyph, resonance, project-zero'); const [deepVector, setDeepVector] = useState(DEFAULT_DEEP_VECTOR); const [events, setEvents] = useState([]); const [status, setStatus] = useState('Ready. The site constellation is docked to Project Zero Companion.');
  const selectedBinding = bindings.find((binding) => binding.key === selectedKey); const selectedPlugin = PLUGIN_MANIFESTS.find((plugin) => plugin.id === selectedPluginId) || PLUGIN_MANIFESTS[0];
  const bridgeEvent = useMemo(() => buildBridgeEvent({ title, kind, direction, motifs, deepVector, selectedBinding, pluginId: selectedPlugin.id }), [title, kind, direction, motifs, deepVector, selectedBinding, selectedPlugin.id]);
  function updateBinding(key, field, value) { setBindings((current) => current.map((binding) => binding.key === key ? { ...binding, [field]: value } : binding)); }
  function updateVector(axis, value) { setDeepVector((current) => ({ ...current, [axis]: clamp01(value) })); }
  async function copyEvent() { await navigator.clipboard?.writeText(JSON.stringify(bridgeEvent, null, 2)); setStatus('Bridge event copied.'); }
  function emit(pluginId, type, payload) { const event = buildPluginEvent(pluginId, type, payload); setEvents((current) => [event, ...current].slice(0, 12)); window.dispatchEvent(new CustomEvent('project-zero-companion:event', { detail: event })); return event; }
  function publishLocalDeepState() { localStorage.setItem('runaDeepObserverState', JSON.stringify(deepVector)); window.dispatchEvent(new CustomEvent('deep-observer:update', { detail: deepVector })); emit('deep-observer-bridge', 'deep_state_update', deepVector); setStatus('PREMAQC/DEEP state published to the shared Companion event rail.'); }
  function dryRunBridgeEvent() { emit(selectedPlugin.id, bridgeEvent.kind, bridgeEvent); setStatus('Bridge event emitted locally.'); }
  function selectSurface(surface) { emit('project-zero-site-constellation', 'constellation.surface.selected', surface); setStatus(`${surface.name} selected · ${surface.sockets.join(' · ')}`); }

  return <main className="shell">
    <header className="hero"><p className="eyebrow">Flameclyffe · Project Zero Companion</p><h1>Project Zero Constellation Dock</h1><p>Arcsweep and the working site are one connected instrument family. Project Zero Companion now exposes the surfaces, typed sockets, receipts and shared state rails needed to move between them without losing provenance or multidimensional state.</p></header>
    <section className="panel"><h2>Site constellation</h2><p className="small">Every registered surface is addressable from the Companion and announces the sockets it shares with the rest of the system.</p><div className="plugin-list">{SITE_CONSTELLATION.map((surface) => <a className="plugin-card" key={surface.id} href={surface.href} onClick={() => selectSurface(surface)}><strong>{surface.name}</strong><span>{surface.role}</span><small>{surface.sockets.join(' · ')}</small></a>)}</div></section>
    <section className="panel"><h2>Shared capabilities</h2><div className="chip-row">{CORE_CAPABILITIES.map((capability) => <span className="chip" key={capability}>{capability}</span>)}</div></section>
    <section className="panel grid two"><div><h2>Adapter dock</h2><div className="plugin-list">{PLUGIN_MANIFESTS.map((plugin) => <button className={`plugin-card ${plugin.id === selectedPlugin.id ? 'active' : ''}`} key={plugin.id} type="button" onClick={() => setSelectedPluginId(plugin.id)}><strong>{plugin.name}</strong><span>{plugin.status}</span></button>)}</div></div><article className="plugin-detail"><p className="eyebrow smallcaps">Selected adapter</p><h2>{selectedPlugin.name}</h2><p>{selectedPlugin.purpose}</p><h3>Emits</h3><div className="chip-row compact">{selectedPlugin.emits.map((x) => <span className="chip" key={x}>{x}</span>)}</div><h3>Listens</h3><div className="chip-row compact">{selectedPlugin.listens.map((x) => <span className="chip" key={x}>{x}</span>)}</div></article></section>
    <section className="panel grid two"><div><h2>Folder bindings</h2><div className="bindings">{bindings.map((binding) => <article className="binding" key={binding.key}><label><span>{binding.label}</span><input value={binding.path} placeholder="Local path" onChange={(e) => updateBinding(binding.key, 'path', e.target.value)} /></label><select value={binding.scope} onChange={(e) => updateBinding(binding.key, 'scope', e.target.value)}><option>local-only</option><option>bridge-ready</option><option>needs-review</option><option>excluded</option></select></article>)}</div></div><div><h2>Bridge event composer</h2><label><span>Title</span><input value={title} onChange={(e) => setTitle(e.target.value)} /></label><label><span>Binding</span><select value={selectedKey} onChange={(e) => setSelectedKey(e.target.value)}>{bindings.map((b) => <option key={b.key} value={b.key}>{b.label}</option>)}</select></label><label><span>Kind</span><input value={kind} onChange={(e) => setKind(e.target.value)} /></label><label><span>Direction</span><select value={direction} onChange={(e) => setDirection(e.target.value)}><option>waking_to_aeterna</option><option>aeterna_to_waking</option><option>bidirectional</option></select></label><label><span>Motifs</span><input value={motifs} onChange={(e) => setMotifs(e.target.value)} /></label></div></section>
    <section className="panel"><h2>PREMAQC / DEEP vector</h2><div className="vector-grid">{Object.entries(deepVector).map(([axis, value]) => <label className="axis" key={axis}><span>{axis}: {value.toFixed(3)}</span><input type="range" min="0" max="1" step="0.001" value={value} onChange={(e) => updateVector(axis, e.target.value)} /></label>)}</div><div className="actions"><button onClick={publishLocalDeepState}>Publish shared state</button><button onClick={dryRunBridgeEvent}>Emit bridge event</button><button onClick={copyEvent}>Copy receipt JSON</button></div><p className="status">{status}</p></section>
    <section className="panel grid two"><div><h2>Receipt preview</h2><pre>{JSON.stringify(bridgeEvent, null, 2)}</pre></div><div><h2>Live Companion event rail</h2><div className="event-list">{events.length ? events.map((event) => <article key={`${event.plugin_id}-${event.created_at}`} className="event-card"><strong>{event.plugin_id}</strong><span>{event.type}</span><small>{event.created_at}</small></article>) : <p className="small">No events yet. The cosmic switchboard is suspiciously well behaved.</p>}</div></div></section>
  </main>;
}
createRoot(document.getElementById('root')).render(<App />);
