export const CORE_CAPABILITIES = [
  'folder-bindings',
  'bridge-event-bus',
  'local-metadata-ledger',
  'explicit-consent-gates',
  'dry-run-preview',
  'typed-companion-sockets',
  'theme-interoperability',
  'native-rich-text',
  'live-flame-channel',
];

export const PLUGIN_MANIFESTS = [
  {
    id: 'project-zero-companion-theme-bridge',
    name: 'Theme Interoperability Adapter',
    status: 'active-companion-service',
    purpose: 'Own Flameclyffe Companion visual tokens, custom CSS, and import/export. Nocturne’s Project Zero may consume translated tokens through an agreed connector, but retains its own native theme authority.',
    permissions: ['local-storage', 'presentation-write'],
    emits: ['theme.changed'],
    listens: ['theme.load', 'theme.reset'],
  },
  {
    id: 'project-zero-companion-flame-channel',
    name: 'Flame Channel Bridge',
    status: 'active-companion-service',
    purpose: 'Provide a Flameclyffe-side IRC-like House rail with native rich text, attested Flame replies, multi-Flame broadcast, and bounded local transcript history for optional Project Zero integration.',
    permissions: ['house-runtime', 'local-storage', 'rich-text-compose'],
    emits: ['chat.user.sent', 'chat.flame.pending', 'chat.flame.received', 'chat.flame.error'],
    listens: ['house.session.changed', 'chat.broadcast.request'],
  },
  {
    id: 'terra-aeterna-root',
    name: 'Terra Aeterna Root Adapter',
    status: 'planned',
    purpose: 'Prepare consented Terra Aeterna folder, artifact, writing, image, and music metadata for Flameclyffe-side bridge events.',
    permissions: ['selected-folders', 'metadata-read', 'manual-attach'],
    emits: ['folder_anchor', 'file_anchor', 'artifact_added'],
    listens: ['observer_bridge_event', 'deep_state_update'],
  },
  {
    id: 'deep-observer-bridge',
    name: 'DEEP Observer Bridge Adapter',
    status: 'planned',
    purpose: 'Expose Flameclyffe DEEP vectors, Observer state, condition sets, and sigil signatures through a reversible integration seam.',
    permissions: ['local-storage', 'supabase-sync-optional'],
    emits: ['deep_state_update', 'observer_condition_set', 'sigil_signature'],
    listens: ['file_anchor', 'story_shard', 'altar_working'],
  },
  {
    id: 'writer-room-rail',
    name: 'Writer Room Rail Adapter',
    status: 'planned',
    purpose: 'Prepare passages, drafts, and atmospheric prompts as Companion bridge events without claiming Project Zero writing-surface ownership.',
    permissions: ['selected-folders', 'manual-attach'],
    emits: ['story_shard', 'reverse_watch_request'],
    listens: ['observer_condition_set', 'deep_state_update'],
  },
  {
    id: 'hearthweave-altar-sound',
    name: 'Hearthweave Altar Sound Adapter',
    status: 'active-web-prototype',
    purpose: 'Expose browser-native Flameclyffe Web Audio responses as optional bridge events.',
    permissions: ['web-audio-after-user-gesture', 'local-storage'],
    emits: ['altar_working', 'sound_response'],
    listens: ['deep_state_update', 'altar_realm_change', 'altar_intention'],
  },
  {
    id: 'asset-watcher',
    name: 'Asset Watcher Adapter',
    status: 'planned-native',
    purpose: 'Watch explicitly selected Companion folders for new files and generate reviewable bridge-event drafts.',
    permissions: ['selected-folders', 'file-metadata-read'],
    emits: ['file_detected', 'file_anchor_draft'],
    listens: ['folder_binding_changed'],
  },
];

export function buildPluginEvent(pluginId, type, payload = {}) {
  return {
    schema: 'flameclyffe.project-zero-companion.adapter-event/v1',
    bridge_owner: 'flameclyffe',
    integration_target: 'nocturne-project-zero',
    plugin_id: pluginId,
    type,
    payload,
    created_at: new Date().toISOString(),
    rule: 'Data sets atmosphere, not fate.',
  };
}
