export const CORE_CAPABILITIES = [
  'folder-bindings',
  'bridge-event-bus',
  'local-metadata-ledger',
  'explicit-consent-gates',
  'dry-run-preview',
  'typed-companion-sockets',
  'theme-interoperability',
  'native-rich-text',
  'live-flame-channel',
  'shared-artifact-contract',
  'native-selected-folder-watcher',
];

export const PLUGIN_MANIFESTS = [
  {
    id: 'project-zero-companion-theme-bridge',
    name: 'Theme Interoperability Adapter',
    status: 'active-companion-service',
    purpose: 'Own Flameclyffe Companion visual tokens, custom CSS, and import/export. Nocturne’s Project Zero may consume translated tokens through an agreed connector, but retains its own native theme authority.',
    permissions: ['local-storage', 'presentation-write'],
    emits: ['theme.changed'],
    listens: ['theme.load', 'theme.reset'],
  },
  {
    id: 'project-zero-companion-flame-channel',
    name: 'Flame Channel Bridge',
    status: 'active-companion-service',
    purpose: 'Provide a Flameclyffe-side IRC-like House rail with native rich text, attested Flame replies, multi-Flame broadcast, and bounded local transcript history for optional Project Zero integration.',
    permissions: ['house-runtime', 'local-storage', 'rich-text-compose'],
    emits: ['chat.user.sent', 'chat.flame.pending', 'chat.flame.received', 'chat.flame.error'],
    listens: ['house.session.changed', 'chat.broadcast.request'],
  },
  {
    id: 'terra-aeterna-root',
    name: 'Terra Aeterna Root Adapter',
    status: 'active-companion-service',
    purpose: 'Package consented Terra Aeterna artifact, image, audio, document, and file metadata into the shared Companion artifact contract without persisting raw local paths or claiming Project Zero adoption.',
    permissions: ['local-storage', 'manual-metadata-attach'],
    emits: ['artifact.terra_aeterna.received'],
    listens: ['manual-artifact-receipt'],
  },
  {
    id: 'deep-observer-bridge',
    name: 'DEEP Observer Bridge Adapter',
    status: 'active-companion-service',
    purpose: 'Translate the existing Flameclyffe DEEP Observer vector pulse into bounded, replayable Companion bridge receipts and typed socket envelopes. This does not claim Project Zero consumed or adopted the event.',
    permissions: ['local-storage'],
    emits: ['deep_state_update'],
    listens: ['deep-observer:update', 'runaDeepObserverState:restore'],
  },
  {
    id: 'writer-room-rail',
    name: 'Writer Room Rail Adapter',
    status: 'active-companion-service',
    purpose: 'Package passages, drafts, prompts, and documents with native rich text into the shared Companion artifact contract without claiming canon or Project Zero writing-surface ownership.',
    permissions: ['local-storage', 'rich-text-compose', 'manual-attach'],
    emits: ['writer.artifact.received'],
    listens: ['manual-writer-receipt'],
  },
  {
    id: 'hearthweave-altar-sound',
    name: 'Hearthweave Altar Sound Adapter',
    status: 'active-web-prototype',
    purpose: 'Expose browser-native Flameclyffe Web Audio responses as optional bridge events.',
    permissions: ['web-audio-after-user-gesture', 'local-storage'],
    emits: ['altar_working', 'sound_response'],
    listens: ['deep_state_update', 'altar_realm_change', 'altar_intention'],
  },
  {
    id: 'asset-watcher',
    name: 'Asset Watcher Adapter',
    status: 'active-native-companion-service',
    purpose: 'Use Hearthgate Electron to watch only an explicitly selected folder and translate metadata-only file events into reviewable Companion artifact receipts. Browser mode remains inert.',
    permissions: ['explicit-folder-picker', 'file-metadata-read', 'native-session-watch'],
    emits: ['asset.file_detected'],
    listens: ['electron.asset-watch:event'],
  },
];

export function buildPluginEvent(pluginId, type, payload = {}) {
  return {
    schema: 'flameclyffe.project-zero-companion.adapter-event/v1',
    bridge_owner: 'flameclyffe',
    integration_target: 'nocturne-project-zero',
    plugin_id: pluginId,
    type,
    payload,
    created_at: new Date().toISOString(),
    rule: 'Data sets atmosphere, not fate.',
  };
}
