'use strict';
const fs = require('fs'); const path = require('path'); const crypto = require('crypto');
function createAlmanacStore({ dataDir }) {
  const root = path.join(dataDir, 'observer-almanac'), catalogPath = path.join(root, 'packets.json');
  async function read() { try { return JSON.parse(await fs.promises.readFile(catalogPath, 'utf8')); } catch (e) { if (e.code !== 'ENOENT') throw e; return { schema: 'hearthgate.observer-almanac/v1', packets: [] }; } }
  async function write(value) { await fs.promises.mkdir(root, { recursive: true }); const tmp = `${catalogPath}.${process.pid}.tmp`; await fs.promises.writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`); await fs.promises.rename(tmp, catalogPath); }
  function clean(input, existing = {}) { const now = new Date().toISOString(), glyphId = String(input.glyphId || input.glyph?.glyph_id || existing.glyphId || '').trim(); if (!glyphId) throw Object.assign(new Error('glyph-id-required'), { code: 'glyph-id-required' }); return { id: existing.id || crypto.randomUUID(), glyphId, capturedAt: input.capturedAt || existing.capturedAt || now, updatedAt: now, register: String(input.register ?? existing.register ?? 'mythience'), continuity: String(input.continuity ?? existing.continuity ?? '').slice(0, 240), locus: { dreaming: String(input.locus?.dreaming ?? existing.locus?.dreaming ?? '').slice(0, 240), waking: String(input.locus?.waking ?? existing.locus?.waking ?? '').slice(0, 240), wakingPrivate: input.locus?.wakingPrivate !== false }, observation: input.observation ?? existing.observation ?? null, vector: input.vector ?? existing.vector ?? null, glyph: input.glyph ?? existing.glyph ?? null, narrative: String(input.narrative ?? existing.narrative ?? '').slice(0, 50000), sourceRefs: Array.isArray(input.sourceRefs) ? [...new Set(input.sourceRefs.map(String).filter(Boolean))].slice(0, 100) : (existing.sourceRefs || []), privacy: String(input.privacy ?? existing.privacy ?? 'private'), consent: String(input.consent ?? existing.consent ?? 'not recorded'), tags: Array.isArray(input.tags) ? input.tags.map(String).filter(Boolean).slice(0, 80) : (existing.tags || []), scores: input.scores ?? existing.scores ?? null, boundary: 'Observation, vector, glyph, narrative, and sources are preserved together without treating interpretation as measurement.' }; }
  async function list() { return read(); }
  async function save(input) { const catalog = await read(), glyphId = String(input.glyphId || input.glyph?.glyph_id || '').trim(), index = catalog.packets.findIndex(packet => packet.glyphId === glyphId); const packet = clean(input, index >= 0 ? catalog.packets[index] : {}); if (index >= 0) catalog.packets[index] = packet; else catalog.packets.unshift(packet); catalog.updatedAt = packet.updatedAt; await write(catalog); return { packet, updated: index >= 0 }; }
  async function get(id) { return (await read()).packets.find(packet => packet.id === id || packet.glyphId === id) || null; }
  async function remove(id) { const catalog = await read(), before = catalog.packets.length; catalog.packets = catalog.packets.filter(packet => packet.id !== id); if (before === catalog.packets.length) return false; await write(catalog); return true; }
  return { list, save, get, remove, catalogPath };
}
module.exports = { createAlmanacStore };
