'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { validateTonePatch, validateConsentProfile, preflightToneSession, mapResponseState, serializeTonePercept } = require('./tone-contract');

const PRESETS = [
  { id: 'dreaming', name: 'Between the Dreaming', description: 'A soft, liminal field: low oceanic pulse beneath a clear upper tone.', visual: 'Sea-green glass, violet depth, liminal light.', frequencyHz: 174, overtoneHz: 417, defaultSeconds: 60, maxSeconds: 600, defaultVolume: 0.08, maxVolume: 0.25, hapticPattern: [40, 120, 40], intensity: 'gentle', warnings: ['May feel immersive. Stop if you feel disoriented or uncomfortable.'] },
  { id: 'loch', name: 'Lochflame', description: 'A slow, cool pulse intended for quiet focus rather than stimulation.', visual: 'Deep water and turquoise refraction.', frequencyHz: 136.1, overtoneHz: 272.2, defaultSeconds: 60, maxSeconds: 600, defaultVolume: 0.07, maxVolume: 0.22, hapticPattern: [30, 180, 30], intensity: 'gentle', warnings: ['Low frequencies may be unpleasant through headphones for some listeners.'] },
  { id: 'hearth', name: 'Hearthfire', description: 'A warm, steady interval with a slightly brighter pulse.', visual: 'Amber glass and intimate warmth.', frequencyHz: 220, overtoneHz: 330, defaultSeconds: 45, maxSeconds: 480, defaultVolume: 0.07, maxVolume: 0.22, hapticPattern: [45, 100, 45], intensity: 'moderate', warnings: ['The brighter interval may feel activating. Begin quietly.'] },
  { id: 'starfall', name: 'Starfall', description: 'Sparse high shimmer over a stable lower anchor.', visual: 'Indigo night and celestial gold.', frequencyHz: 196, overtoneHz: 523.25, defaultSeconds: 45, maxSeconds: 300, defaultVolume: 0.05, maxVolume: 0.18, hapticPattern: [20, 220, 20], intensity: 'moderate', warnings: ['Contains a higher tone. Avoid if high frequencies cause discomfort.'] },
  { id: 'obsidian', name: 'Black Glass', description: 'Minimal sound, long spaces, and a low unobtrusive anchor.', visual: 'Graphite, silver edges, restrained glow.', frequencyHz: 110, overtoneHz: 220, defaultSeconds: 60, maxSeconds: 600, defaultVolume: 0.05, maxVolume: 0.18, hapticPattern: [25, 250, 25], intensity: 'gentle', warnings: ['Very low tones may be more felt than heard on some equipment.'] },
];

function createToneStore({ dataDir }) {
  const root = path.join(dataDir, 'tone-lab');
  const sessionsPath = path.join(root, 'sessions.json');
  const presetsPath = path.join(root, 'presets.json');
  const profilesPath = path.join(root, 'accessibility-profiles.json');
  const consentProfilesPath = path.join(root, 'consent-profiles.json');
  async function read() { try { return JSON.parse(await fs.promises.readFile(sessionsPath, 'utf8')); } catch (e) { if (e.code !== 'ENOENT') throw e; return { schema: 'hearthgate.tone-sessions/v1', sessions: [] }; } }
  async function write(value) { await fs.promises.mkdir(root, { recursive: true }); const tmp = `${sessionsPath}.${process.pid}.tmp`; await fs.promises.writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`); await fs.promises.rename(tmp, sessionsPath); }
  async function readPresetConfig() { try { return JSON.parse(await fs.promises.readFile(presetsPath, 'utf8')); } catch (e) { if (e.code !== 'ENOENT') throw e; return { schema: 'hearthgate.tone-preset-config/v1', presets: [] }; } }
  async function writePresetConfig(value) { await fs.promises.mkdir(root, { recursive: true }); const tmp = `${presetsPath}.${process.pid}.tmp`; await fs.promises.writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`); await fs.promises.rename(tmp, presetsPath); }
  function cleanPreset(input, existing = {}) {
    return { ...validateTonePatch({ ...input, custom: true }, existing), custom: true };
  }
  async function rawPresets() { const config = await readPresetConfig(); const overrides = new Map(config.presets.map(p => [p.id, p])); return [...PRESETS.map(p => overrides.get(p.id) ? { ...p, ...overrides.get(p.id), custom: false, configured: true } : { ...p, custom: false }), ...config.presets.filter(p => !PRESETS.some(seed => seed.id === p.id))]; }
  async function presets() { return (await rawPresets()).map(({ frequencyHz, overtoneHz, hapticPattern, ...publicPreset }) => ({ ...publicPreset, audio: { frequencyHz, overtoneHz }, haptics: { pattern: hapticPattern } })); }
  async function savePreset(input) { const config = await readPresetConfig(); const seed = PRESETS.find(p => p.id === input.id); const index = config.presets.findIndex(p => p.id === input.id); const preset = cleanPreset(input, index >= 0 ? config.presets[index] : seed || {}); if (index >= 0) config.presets[index] = preset; else config.presets.push(preset); config.updatedAt = preset.updatedAt; await writePresetConfig(config); return (await presets()).find(p => p.id === preset.id); }
  async function removePreset(id) { const config = await readPresetConfig(); const before = config.presets.length; config.presets = config.presets.filter(p => p.id !== id); if (config.presets.length === before) return false; await writePresetConfig(config); return true; }
  async function profiles() { try { return JSON.parse(await fs.promises.readFile(profilesPath, 'utf8')); } catch (e) { if (e.code !== 'ENOENT') throw e; return { schema: 'hearthgate.tone-accessibility/v1', profiles: [{ id: 'speakers', name: 'Device speakers', deviceKind: 'speakers', volumeCeiling: .18, frequencyMinHz: 80, frequencyMaxHz: 12000, hapticsAllowed: false, notes: 'Begin quietly; room acoustics can create additional artefacts.' }, { id: 'shokz', name: 'Shokz / bone conduction', deviceKind: 'bone-conduction', volumeCeiling: .16, frequencyMinHz: 80, frequencyMaxHz: 12000, hapticsAllowed: false, notes: 'User-configurable bone-conduction listening profile.' }, { id: 'baha-hearing-aid', name: 'BAHA / hearing-aid route', deviceKind: 'hearing-accessibility', volumeCeiling: .12, frequencyMinHz: 100, frequencyMaxHz: 8000, hapticsAllowed: false, notes: 'Hearthgate stores preferences only; routing remains in the operating system or hearing-device app.' }, { id: 'woofer', name: 'Woojer / haptic transducer', deviceKind: 'haptic', volumeCeiling: .12, frequencyMinHz: 40, frequencyMaxHz: 300, hapticsAllowed: true, notes: 'Low-frequency/haptic profile. Begin at the lowest comfortable intensity.' }] }; } }
  async function saveProfiles(input) { const current = await profiles(), list = Array.isArray(input.profiles) ? input.profiles : current.profiles; const clean = { schema: 'hearthgate.tone-accessibility/v1', updatedAt: new Date().toISOString(), profiles: list.slice(0, 50).map((p, index) => ({ id: String(p.id || p.name || `profile-${index}`).toLowerCase().replace(/[^a-z0-9-]+/g, '-').slice(0, 60), name: String(p.name || 'Output profile').slice(0, 100), deviceKind: String(p.deviceKind || 'custom').slice(0, 80), volumeCeiling: Math.max(0, Math.min(Number(p.volumeCeiling) || 0, .35)), frequencyMinHz: Math.max(20, Math.min(Number(p.frequencyMinHz) || 20, 16000)), frequencyMaxHz: Math.max(20, Math.min(Number(p.frequencyMaxHz) || 16000, 16000)), hapticsAllowed: p.hapticsAllowed === true, notes: String(p.notes || '').slice(0, 2000) })) }; const tmp = `${profilesPath}.${process.pid}.tmp`; await fs.promises.mkdir(root, { recursive: true }); await fs.promises.writeFile(tmp, `${JSON.stringify(clean, null, 2)}\n`); await fs.promises.rename(tmp, profilesPath); return clean; }
  async function consentProfiles() { try { return JSON.parse(await fs.promises.readFile(consentProfilesPath, 'utf8')); } catch (e) { if (e.code !== 'ENOENT') throw e; return { schema: 'hearthgate.tone-consent-profiles/v1', profiles: [validateConsentProfile()] }; } }
  async function saveConsentProfile(input = {}) { const catalog = await consentProfiles(); const requestedId = input.profileId || input.profile_id || 'default'; const index = catalog.profiles.findIndex(profile => profile.profileId === requestedId); const profile = validateConsentProfile(input, index >= 0 ? catalog.profiles[index] : {}); if (index >= 0) catalog.profiles[index] = profile; else catalog.profiles.push(profile); catalog.updatedAt = profile.updatedAt; await fs.promises.mkdir(root, { recursive: true }); const tmp = `${consentProfilesPath}.${process.pid}.tmp`; await fs.promises.writeFile(tmp, `${JSON.stringify(catalog, null, 2)}\n`); await fs.promises.rename(tmp, consentProfilesPath); return profile; }
  async function preflight(input = {}) { const patch = (await rawPresets()).find(item => item.id === input.presetId || item.id === input.patchId); if (!patch) throw Object.assign(new Error('unknown-tone-preset'), { code: 'unknown-tone-preset' }); const profileCatalog = await consentProfiles(); const profile = profileCatalog.profiles.find(item => item.profileId === (input.profileId || 'default')) || profileCatalog.profiles[0]; return preflightToneSession({ patch: validateTonePatch(patch), profile, request: input }); }
  async function list() { return read(); }
  async function record(input = {}) {
    const preset = (await rawPresets()).find(item => item.id === input.presetId); if (!preset) throw Object.assign(new Error('unknown-tone-preset'), { code: 'unknown-tone-preset' });
    const gate = await preflight(input); if (!gate.allowed) throw Object.assign(new Error(gate.reasons[0]), { code: gate.reasons[0], preflight: gate });
    const response = { comfort: String(input.response?.comfort || 'not recorded').slice(0, 40), body: String(input.response?.body || '').slice(0, 4000), emotion: String(input.response?.emotion || '').slice(0, 4000), imagery: String(input.response?.imagery || '').slice(0, 4000), notes: String(input.response?.notes || '').slice(0, 8000), activation: input.response?.activation, valence: input.response?.valence, groundedness: input.response?.groundedness };
    const state = mapResponseState({ ...response, stoppedByUser: input.stoppedByUser === true });
    const session = { schema: 'hearthgate.tone-response-ledger/v1', id: crypto.randomUUID(), patchId: preset.id, presetId: preset.id, patchName: preset.name, presetName: preset.name, consentProfileId: input.profileId || 'default', startedAt: input.startedAt || null, endedAt: input.endedAt || new Date().toISOString(), durationSeconds: gate.limits.durationSeconds, volume: gate.limits.volume, maxGainDb: gate.limits.maxGainDb, audioEnabled: input.audioEnabled === true, hapticsEnabled: input.hapticsEnabled === true, consent: true, stoppedByUser: input.stoppedByUser === true, stopWord: input.stopWord ? String(input.stopWord).toLowerCase().slice(0, 40) : null, response, state, classification: 'user-authored sensory response', provenance: { instrument: 'Hearthgate Tone Engine Lab', patchSchema: 'hearthgate.tone-patch/v1', presetVersion: 1 }, boundary: state.claimBoundary };
    session.percept = serializeTonePercept(session);
    const catalog = await read(); catalog.sessions.unshift(session); catalog.sessions = catalog.sessions.slice(0, 1000); catalog.updatedAt = session.endedAt; await write(catalog); return session;
  }
  return { presets, list, record, preflight, savePreset, removePreset, profiles, saveProfiles, consentProfiles, saveConsentProfile, sessionsPath, presetsPath, profilesPath, consentProfilesPath };
}
module.exports = { createToneStore, PRESETS };
