export const routeLatticeMetric = Object.freeze({
  id: 'route-canon-unit-lattice',
  dimensions: Object.freeze(['canon', 'instrument', 'archive', 'visual', 'access', 'ritual']),
  weights: Object.freeze({
    canon: 1.25,
    instrument: 1,
    archive: 0.9,
    visual: 1,
    access: 1.15,
    ritual: 0.95,
  }),
  scales: Object.freeze({
    canon: 1,
    instrument: 1,
    archive: 1,
    visual: 1,
    access: 1,
    ritual: 1,
  }),
  unitDistance: 0.9,
  tolerance: 0.24,
  epsilon: 1e-9,
  edgeLimit: 42,
});

export const routeLatticeConfig = Object.freeze({
  metric: routeLatticeMetric,
  window: Object.freeze({
    requireVisible: true,
    requireConsent: true,
    includeKinds: Object.freeze(['core', 'lab', 'archive', 'gallery', 'instrument']),
    limit: 24,
  }),
  tree: Object.freeze({
    rootId: 'harbour',
    defaultFocusId: 'harbour',
    defaultOpenIds: Object.freeze(['harbour', 'starwell']),
    width: 840,
    rootY: 590,
    levelGap: 128,
    paddingX: 70,
  }),
  projection: Object.freeze({
    mode: 'radial',
    radius: 255,
    centre: Object.freeze({ x: 420, y: 330 }),
    kindOrder: Object.freeze(['core', 'instrument', 'lab', 'gallery', 'archive']),
  }),
});

export const routeLatticeNodes = Object.freeze([
  {
    id: 'harbour',
    kind: 'core',
    label: 'Harbour Route Map',
    href: '../../harbor.html',
    vector: Object.freeze({ canon: 0.65, instrument: 0.35, archive: 0.65, visual: 0.35, access: 0.85, ritual: 0.55 }),
    meta: Object.freeze({ visible: true, consent: true, note: 'The paddling dock and route ledger.', action: 'Open the route map', order: 0 }),
  },
  {
    id: 'starwell',
    parentId: 'harbour',
    kind: 'instrument',
    label: 'STARWELL',
    href: '../../starwell/',
    vector: Object.freeze({ canon: 0.8, instrument: 0.95, archive: 0.45, visual: 0.75, access: 0.5, ritual: 0.65 }),
    meta: Object.freeze({ visible: true, consent: true, note: 'Canonical observatory and glyph instrument lane.', action: 'Enter STARWELL', order: 1 }),
  },
  {
    id: 'deep-observer',
    parentId: 'starwell',
    kind: 'instrument',
    label: 'DEEP Observer',
    href: '../../starwell/deep-observer/',
    vector: Object.freeze({ canon: 0.72, instrument: 0.95, archive: 0.38, visual: 0.82, access: 0.48, ritual: 0.55 }),
    meta: Object.freeze({ visible: true, consent: true, note: 'Presence, coherence, rhythm, entropy, memory, attention.', action: 'Open DEEP Observer', order: 1 }),
  },
  {
    id: 'pocket-concordance',
    parentId: 'harbour',
    kind: 'instrument',
    label: 'Pocket Concordance Lens',
    href: '../../pocket-concordance-lens/',
    vector: Object.freeze({ canon: 0.55, instrument: 0.72, archive: 0.42, visual: 0.6, access: 0.95, ritual: 0.58 }),
    meta: Object.freeze({ visible: true, consent: true, note: 'Camera and anchor fallback build.', action: 'Open Pocket Lens', order: 2 }),
  },
  {
    id: 'unit-resonance-lab',
    parentId: 'starwell',
    kind: 'lab',
    label: 'Unit Resonance Lab',
    href: '../../starwell-react-lab/unit-resonance-lab/',
    vector: Object.freeze({ canon: 0.55, instrument: 0.75, archive: 0.3, visual: 0.72, access: 0.35, ritual: 0.38 }),
    meta: Object.freeze({ visible: true, consent: true, note: 'The first math-kernel lab route.', action: 'Open resonance lab', order: 2 }),
  },
  {
    id: 'lattice-lab',
    parentId: 'starwell',
    kind: 'lab',
    label: 'Unit Resonance Lattice',
    href: './',
    vector: Object.freeze({ canon: 0.62, instrument: 0.7, archive: 0.45, visual: 0.78, access: 0.55, ritual: 0.42 }),
    meta: Object.freeze({ visible: true, consent: true, note: 'This page: a living route tree powered by the lattice kernel.', action: 'Stay in this lab', order: 3 }),
  },
  {
    id: 'atelier',
    parentId: 'harbour',
    kind: 'gallery',
    label: 'Atelier',
    href: '../../atelier.html',
    vector: Object.freeze({ canon: 0.7, instrument: 0.25, archive: 0.62, visual: 0.98, access: 0.35, ritual: 0.58 }),
    meta: Object.freeze({ visible: true, consent: true, note: 'Image and art canon bench.', action: 'Open Atelier', order: 3 }),
  },
  {
    id: 'drift-hub',
    parentId: 'harbour',
    kind: 'archive',
    label: 'Drift Hub',
    href: '../../drift-hub.html',
    vector: Object.freeze({ canon: 0.48, instrument: 0.55, archive: 0.92, visual: 0.55, access: 0.4, ritual: 0.68 }),
    meta: Object.freeze({ visible: true, consent: true, note: 'Older drift and wave-room routing.', action: 'Open Drift Hub', order: 4 }),
  },
  {
    id: 'studio',
    parentId: 'drift-hub',
    kind: 'archive',
    label: 'Studio',
    href: '../../studio.html',
    vector: Object.freeze({ canon: 0.52, instrument: 0.42, archive: 0.85, visual: 0.7, access: 0.35, ritual: 0.48 }),
    meta: Object.freeze({ visible: true, consent: true, note: 'Workshop lane for older prototypes.', action: 'Open Studio', order: 1 }),
  },
  {
    id: 'moonmere-wiki',
    parentId: 'harbour',
    kind: 'core',
    label: 'Moonmere Wiki',
    href: 'https://moonmere-wiki.netlify.app',
    vector: Object.freeze({ canon: 0.95, instrument: 0.25, archive: 0.88, visual: 0.72, access: 0.48, ritual: 0.88 }),
    meta: Object.freeze({ visible: true, consent: true, note: 'Luna, Eira, Moonmere Gate, and wiki canon route.', action: 'Open Moonmere Wiki', order: 5 }),
  },
  {
    id: 'feather-to-flame',
    parentId: 'harbour',
    kind: 'core',
    label: 'Feather to Flame',
    href: 'https://feathertoflame.netlify.app',
    vector: Object.freeze({ canon: 0.82, instrument: 0.32, archive: 0.68, visual: 0.7, access: 0.55, ritual: 0.92 }),
    meta: Object.freeze({ visible: true, consent: true, note: 'Public flame-facing house route.', action: 'Open Feather to Flame', order: 6 }),
  },
]);
