export const SIGNAL_SOURCE_ARRAY = [
  {
    id: 'radio-jove-live',
    name: 'Radio JOVE Live Observatory',
    provider: 'NASA Radio JOVE Project / K4LED',
    availability: 'live',
    cadence: 'continuous',
    families: ['jovian', 'solar', 'galactic', 'terrestrial-radio'],
    frequencyLabel: '16–24 MHz spectrograph · 20.1 MHz audio',
    description: 'One continuously visible low-frequency ear for Jupiter, solar bursts, the Milky Way background, lightning, ionospheric effects, and local RFI.',
    officialUrl: 'https://radiojove.gsfc.nasa.gov/',
    openUrl: 'https://youtube.com/channel/UCtawz3MnMBwjz9ShhSC0ygQ/live',
    recordModes: ['display-media', 'audio', 'session-receipt'],
  },
  {
    id: 'e-callisto-global',
    name: 'e-CALLISTO Global Solar Radio Network',
    provider: 'FHNW / IRSOL e-CALLISTO',
    availability: 'near-live',
    cadence: 'station uploads approximately every 15 minutes',
    families: ['solar-radio', 'type-ii-bursts', 'type-iii-bursts', 'dynamic-spectra'],
    frequencyLabel: 'Station-dependent; network spans many radio bands',
    description: 'A world-wide array of solar spectrometers with FITS files, quicklooks, daily spectra, and light curves from many stations.',
    officialUrl: 'https://www.e-callisto.org/Data/data.html',
    openUrl: 'https://soleil.i4ds.ch/solarradio/callistoQuicklooks/',
    recordModes: ['display-media', 'file-ingest', 'session-receipt'],
  },
  {
    id: 'brams-live-meteor',
    name: 'BRAMS Radio Meteor Spectrogram',
    provider: 'Royal Belgian Institute for Space Aeronomy',
    availability: 'near-live',
    cadence: 'spectrogram refreshed every 5 minutes',
    families: ['meteor-scatter', 'upper-atmosphere', 'forward-scatter'],
    frequencyLabel: '49.97 MHz beacon · 2.5 kHz receiver bandwidth',
    description: 'Continuous radio-meteor monitoring with five-minute WAV records and live spectrograms from the Belgian network.',
    officialUrl: 'https://brams.aeronomie.be/',
    openUrl: 'https://brams.aeronomie.be/brams-tv',
    recordModes: ['display-media', 'audio', 'file-ingest', 'session-receipt'],
  },
  {
    id: 'superdarn-live-hf',
    name: 'SuperDARN HF Radar Array',
    provider: 'SuperDARN Canada and partner institutions',
    availability: 'live',
    cadence: 'packet stream per radar transmission/return cycle',
    families: ['ionosphere', 'auroral-radar', 'hf-transmission', 'sky-noise'],
    frequencyLabel: 'Dynamic HF radar frequencies',
    description: 'A global scientific radar network exposing live transmitting state, sky noise, operating frequency, and returned-echo products.',
    officialUrl: 'https://superdarn.ca/',
    openUrl: 'https://superdarn.ca/receiver-info',
    recordModes: ['display-media', 'websocket-adapter', 'session-receipt'],
  },
  {
    id: 'noaa-solar-radio-flux',
    name: 'NOAA Solar Radio Flux',
    provider: 'NOAA Space Weather Prediction Center',
    availability: 'live-data',
    cadence: 'continuously updated JSON service',
    families: ['solar-radio-flux', 'space-weather-context'],
    frequencyLabel: 'Multi-frequency solar radio flux observations',
    description: 'Machine-readable solar radio flux values for correlation beside spectrograph observations.',
    officialUrl: 'https://www.swpc.noaa.gov/products/solar-radio-flux-plots',
    openUrl: 'https://services.swpc.noaa.gov/json/solar-radio-flux.json',
    dataEndpoints: [
      'https://services.swpc.noaa.gov/json/solar-radio-flux.json',
      'https://services.swpc.noaa.gov/json/planetary_k_index_1m.json'
    ],
    recordModes: ['json-snapshot', 'timed-json-series', 'session-receipt'],
  },
  {
    id: 'dsn-now',
    name: 'Deep Space Network Now',
    provider: 'NASA Jet Propulsion Laboratory',
    availability: 'live-status',
    cadence: 'updated every 5 seconds',
    families: ['spacecraft-radio-links', 'uplink', 'downlink', 'deep-space-telemetry'],
    frequencyLabel: 'Mission and antenna dependent',
    description: 'Live state of the DSN dishes, spacecraft contacts, data rates, and signal light-time across the solar system.',
    officialUrl: 'https://eyes.nasa.gov/apps/dsn-now/',
    openUrl: 'https://eyes.nasa.gov/apps/dsn-now/',
    recordModes: ['display-media', 'status-snapshot', 'session-receipt'],
  },
  {
    id: 'chime-frb-voevents',
    name: 'CHIME/FRB Real-Time Alerts',
    provider: 'CHIME/FRB Collaboration',
    availability: 'live-alerts',
    cadence: 'event-driven VOEvent service',
    families: ['fast-radio-bursts', 'transients', 'voevent'],
    frequencyLabel: 'CHIME 400–800 MHz band',
    description: 'Public real-time alerts for newly detected fast radio burst candidates; connection uses the CHIME/FRB VOEvent service.',
    officialUrl: 'https://chime-frb-open-data.github.io/voevents/',
    openUrl: 'https://chime-frb-open-data.github.io/voevents/',
    recordModes: ['voevent-adapter', 'event-ledger', 'session-receipt'],
  },
  {
    id: 'chime-frb-open-data',
    name: 'CHIME/FRB Dynamic Spectra Archive',
    provider: 'CHIME/FRB Collaboration',
    availability: 'archive',
    cadence: 'release-based',
    families: ['fast-radio-bursts', 'dynamic-spectra', 'filterbank', 'hdf5'],
    frequencyLabel: 'Primarily 400–800 MHz',
    description: 'Waterfalls, intensity data, baseband-derived products, catalogues, and analysis examples for recorded FRBs.',
    officialUrl: 'https://chime-frb-open-data.github.io/',
    openUrl: 'https://chime-frb-open-data.github.io/data-releases/',
    recordModes: ['file-ingest', 'archive-receipt'],
  },
  {
    id: 'breakthrough-listen-archive',
    name: 'Breakthrough Listen Open Data',
    provider: 'Berkeley SETI Research Center / Breakthrough Listen',
    availability: 'archive',
    cadence: 'observation releases',
    families: ['technosignatures', 'stellar-targets', 'filterbank', 'hdf5', 'baseband'],
    frequencyLabel: 'Telescope and receiver dependent',
    description: 'Professional telescope observations from Green Bank, Parkes, and other Listen campaigns for independent technosignature sifting.',
    officialUrl: 'https://seti.berkeley.edu/opendata/',
    openUrl: 'https://seti.berkeley.edu/opendata/',
    recordModes: ['file-ingest', 'archive-receipt'],
  },
  {
    id: 'local-sdr-array',
    name: 'Local STARWELL SDR Array',
    provider: 'Hearthfire / STARWELL',
    availability: 'hardware-adapter',
    cadence: 'continuous when receiver is connected',
    families: ['local-rf', 'jovian', 'solar', 'galactic', 'meteor', 'terrestrial-radio'],
    frequencyLabel: 'Receiver and antenna dependent',
    description: 'Our own antenna and SDR path: direct IQ, audio, waterfall, gain state, calibration, and uninterrupted local recording.',
    officialUrl: '/starwell/signal-well/',
    openUrl: '/starwell/signal-well/',
    recordModes: ['iq-recording', 'audio', 'numeric-waterfall', 'session-receipt'],
  },
];

export function sourceById(sourceId) {
  return SIGNAL_SOURCE_ARRAY.find((source) => source.id === sourceId) || null;
}

export function selectedSources(sourceIds) {
  const selected = new Set(sourceIds);
  return SIGNAL_SOURCE_ARRAY.filter((source) => selected.has(source.id));
}

export function sourceArrayCoverage(sources = SIGNAL_SOURCE_ARRAY) {
  return [...new Set(sources.flatMap((source) => source.families))].sort();
}
