alter table public.arcsweep_feedback_cycles
  add column if not exists continuity_packet_id text;

update public.arcsweep_feedback_cycles
set continuity_packet_id = concat('braid:', world_id, ':', cycle_id)
where continuity_packet_id is null;

create or replace function public.set_arcsweep_feedback_cycle_continuity()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
  if new.continuity_packet_id is null then
    new.continuity_packet_id := concat('braid:', new.world_id, ':', new.cycle_id);
  end if;
  return new;
end;
$$;

drop trigger if exists arcsweep_feedback_cycle_continuity_default on public.arcsweep_feedback_cycles;
create trigger arcsweep_feedback_cycle_continuity_default
before insert on public.arcsweep_feedback_cycles
for each row execute function public.set_arcsweep_feedback_cycle_continuity();

revoke all on function public.set_arcsweep_feedback_cycle_continuity() from public, anon, authenticated;
grant execute on function public.set_arcsweep_feedback_cycle_continuity() to service_role;

alter table public.arcsweep_feedback_cycles
  alter column continuity_packet_id set not null;

create unique index if not exists arcsweep_feedback_cycles_continuity_packet_idx
  on public.arcsweep_feedback_cycles (continuity_packet_id);

drop policy if exists "accepted Arcsweep feedback cycles are readable" on public.arcsweep_feedback_cycles;
drop policy if exists "sealed House Runtime reads feedback cycles" on public.arcsweep_feedback_cycles;
create policy "sealed House Runtime reads feedback cycles"
  on public.arcsweep_feedback_cycles for select to anon, authenticated
  using (false);

revoke all on public.arcsweep_feedback_cycles from anon, authenticated;
grant select on public.arcsweep_feedback_cycles to service_role;

alter table public.arcsweep_feedback_reviews
  add column if not exists continuity_packet_id text;

update public.arcsweep_feedback_reviews as review
set continuity_packet_id = cycle.continuity_packet_id
from public.arcsweep_feedback_cycles as cycle
where review.cycle_id = cycle.cycle_id
  and review.continuity_packet_id is null;

alter table public.arcsweep_feedback_reviews
  alter column continuity_packet_id set not null;

grant select, insert on public.arcsweep_feedback_reviews to service_role;

create index if not exists arcsweep_feedback_reviews_continuity_packet_idx
  on public.arcsweep_feedback_reviews (continuity_packet_id);

alter table public.arcsweep_deep_time_records
  add column if not exists continuity_packet_id text;

update public.arcsweep_deep_time_records as deep_time
set continuity_packet_id = cycle.continuity_packet_id
from public.arcsweep_feedback_cycles as cycle
where deep_time.cycle_id = cycle.cycle_id
  and deep_time.continuity_packet_id is null;

alter table public.arcsweep_deep_time_records
  alter column continuity_packet_id set not null;

grant select, insert on public.arcsweep_deep_time_records to service_role;

create index if not exists arcsweep_deep_time_records_continuity_packet_idx
  on public.arcsweep_deep_time_records (continuity_packet_id);

create unique index if not exists arcsweep_deep_time_records_sequence_lambda_idx
  on public.arcsweep_deep_time_records (world_id, sequence_id, lambda);

create table if not exists public.house_runtime_events (
  event_sequence bigint generated by default as identity primary key,
  event_id text not null unique,
  idempotency_key text not null unique,
  continuity_packet_id text not null references public.arcsweep_feedback_cycles(continuity_packet_id),
  world_id text not null,
  cycle_id text not null references public.arcsweep_feedback_cycles(cycle_id),
  event_type text not null check (event_type in (
    'observation-receipted',
    'review-accepted',
    'review-archived',
    'review-discarded',
    'deeptime-admitted'
  )),
  actor_id text not null,
  occurred_at timestamptz not null,
  packet_id text not null,
  packet_fingerprint text not null check (packet_fingerprint ~ '^[0-9a-f]{64}$'),
  source_receipt_ids jsonb not null default '[]'::jsonb check (jsonb_typeof(source_receipt_ids) = 'array'),
  payload jsonb not null,
  created_at timestamptz not null default now(),
  check (payload ->> 'schema' = 'hearthgate.runtime-braid-event/v1'),
  check (payload ->> 'event_id' = event_id),
  check (payload ->> 'event_type' = event_type),
  check (payload ->> 'idempotency_key' = idempotency_key),
  check (payload ->> 'continuity_packet_id' = continuity_packet_id),
  check (payload ->> 'world_id' = world_id),
  check (payload ->> 'cycle_id' = cycle_id),
  check (payload ->> 'actor_id' = actor_id),
  check ((payload ->> 'occurred_at')::timestamptz = occurred_at),
  check (payload ->> 'packet_id' = packet_id),
  check (payload ->> 'packet_fingerprint' = packet_fingerprint),
  check (payload -> 'source_receipt_ids' = source_receipt_ids)
);

create index if not exists house_runtime_events_world_sequence_idx
  on public.house_runtime_events (world_id, event_sequence desc);

create index if not exists house_runtime_events_continuity_sequence_idx
  on public.house_runtime_events (continuity_packet_id, event_sequence);

create or replace function public.prevent_house_runtime_event_mutation()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
  raise exception 'House Runtime events are append-only';
end;
$$;

drop trigger if exists house_runtime_events_append_only on public.house_runtime_events;
create trigger house_runtime_events_append_only
before update or delete on public.house_runtime_events
for each row execute function public.prevent_house_runtime_event_mutation();

revoke all on function public.prevent_house_runtime_event_mutation() from public, anon, authenticated;
grant execute on function public.prevent_house_runtime_event_mutation() to service_role;

alter table public.house_runtime_events enable row level security;

drop policy if exists "sealed House Runtime owns braid events" on public.house_runtime_events;
create policy "sealed House Runtime owns braid events"
  on public.house_runtime_events for select to anon, authenticated
  using (false);

revoke all on public.house_runtime_events from anon, authenticated;
grant select, insert on public.house_runtime_events to service_role;
grant usage, select on sequence public.house_runtime_events_event_sequence_seq to service_role;

create or replace function public.house_runtime_apply_observation_command(p_command jsonb)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_schema text := p_command ->> 'schema';
  v_command_id text := p_command ->> 'command_id';
  v_action text := p_command ->> 'action';
  v_cycle_id text := p_command ->> 'cycle_id';
  v_review jsonb := p_command -> 'review_row';
  v_deep_time jsonb := p_command -> 'deep_time_row';
  v_event jsonb := p_command -> 'event_row';
  v_cycle public.arcsweep_feedback_cycles%rowtype;
  v_existing_review public.arcsweep_feedback_reviews%rowtype;
  v_existing_deep_time public.arcsweep_deep_time_records%rowtype;
  v_previous_deep_time public.arcsweep_deep_time_records%rowtype;
  v_existing_event public.house_runtime_events%rowtype;
  v_event_sequence bigint;
begin
  if v_schema <> 'hearthgate.runtime-braid-command/v1' then
    raise exception 'Unsupported House Runtime braid command schema';
  end if;
  if coalesce(v_command_id, '') = '' or coalesce(v_cycle_id, '') = '' then
    raise exception 'House Runtime braid command and cycle identifiers are required';
  end if;
  if v_action not in ('review-observation', 'admit-deeptime') then
    raise exception 'Unsupported House Runtime braid command action';
  end if;

  select * into v_existing_event
  from public.house_runtime_events
  where idempotency_key = v_command_id;
  if found then
    if v_existing_event.cycle_id <> v_cycle_id
      or (v_action = 'review-observation' and v_existing_event.event_type <> concat('review-', v_review ->> 'decision'))
      or (v_action = 'admit-deeptime' and v_existing_event.event_type <> 'deeptime-admitted') then
      raise exception 'House Runtime command id is already bound to a different lineage';
    end if;
    return jsonb_build_object(
      'applied', false,
      'idempotent', true,
      'event_id', v_existing_event.event_id,
      'event_sequence', v_existing_event.event_sequence,
      'continuity_packet_id', v_existing_event.continuity_packet_id
    );
  end if;

  perform pg_advisory_xact_lock(hashtextextended(concat('house-runtime-cycle:', v_cycle_id), 0));
  select * into v_cycle
  from public.arcsweep_feedback_cycles
  where cycle_id = v_cycle_id;
  if not found then
    raise exception 'Observation cycle does not exist';
  end if;

  if v_event is null
    or v_event ->> 'event_id' is null
    or v_event ->> 'idempotency_key' <> v_command_id
    or v_event ->> 'cycle_id' <> v_cycle_id
    or v_event ->> 'world_id' <> v_cycle.world_id
    or v_event ->> 'continuity_packet_id' <> v_cycle.continuity_packet_id then
    raise exception 'Runtime Braid Event does not match the command lineage';
  end if;

  if v_action = 'review-observation' then
    if v_review is null
      or v_review ->> 'cycle_id' <> v_cycle_id
      or v_review ->> 'world_id' <> v_cycle.world_id
      or v_review ->> 'continuity_packet_id' <> v_cycle.continuity_packet_id
      or v_review ->> 'decision' not in ('accepted', 'archived', 'discarded') then
      raise exception 'Observation review does not match the command lineage';
    end if;
    if v_event ->> 'event_type' <> concat('review-', v_review ->> 'decision') then
      raise exception 'Runtime Braid review event type does not match the human decision';
    end if;

    insert into public.arcsweep_feedback_reviews (
      review_receipt_id,
      cycle_id,
      continuity_packet_id,
      world_id,
      observation_source,
      decision,
      reviewed_by,
      reviewed_at,
      payload
    ) values (
      v_review ->> 'review_receipt_id',
      v_review ->> 'cycle_id',
      v_review ->> 'continuity_packet_id',
      v_review ->> 'world_id',
      v_review ->> 'observation_source',
      v_review ->> 'decision',
      v_review ->> 'reviewed_by',
      (v_review ->> 'reviewed_at')::timestamptz,
      v_review -> 'payload'
    )
    on conflict (cycle_id) do nothing;

    select * into v_existing_review
    from public.arcsweep_feedback_reviews
    where cycle_id = v_cycle_id;
    if v_existing_review.review_receipt_id <> v_review ->> 'review_receipt_id'
      or v_existing_review.decision <> v_review ->> 'decision' then
      raise exception 'Observation cycle already has a different human review';
    end if;
  else
    if v_deep_time is null
      or v_deep_time ->> 'cycle_id' <> v_cycle_id
      or v_deep_time ->> 'world_id' <> v_cycle.world_id
      or v_deep_time ->> 'continuity_packet_id' <> v_cycle.continuity_packet_id then
      raise exception 'DEEPTime record does not match the command lineage';
    end if;
    if v_event ->> 'event_type' <> 'deeptime-admitted' then
      raise exception 'Runtime Braid DEEPTime event type does not match the command';
    end if;

    select * into v_existing_review
    from public.arcsweep_feedback_reviews
    where cycle_id = v_cycle_id;
    if not found or v_existing_review.decision <> 'accepted' then
      raise exception 'DEEPTime admission requires an accepted human review';
    end if;
    if v_existing_review.review_receipt_id <> v_deep_time ->> 'review_receipt_id' then
      raise exception 'DEEPTime admission names the wrong human review receipt';
    end if;

    perform pg_advisory_xact_lock(hashtextextended(concat(v_cycle.world_id, ':', v_deep_time ->> 'sequence_id'), 0));
    select * into v_previous_deep_time
    from public.arcsweep_deep_time_records
    where world_id = v_cycle.world_id
      and sequence_id = v_deep_time ->> 'sequence_id'
    order by lambda desc
    limit 1;
    if found and (v_deep_time ->> 'lambda')::bigint <> v_previous_deep_time.lambda + 1 then
      raise exception 'DEEPTime sequence advanced; rebuild the admission from the latest accepted record';
    end if;
    if found and v_deep_time #>> '{payload,interval,previous_record_id}' <> v_previous_deep_time.record_id then
      raise exception 'DEEPTime predecessor does not match the latest accepted record';
    end if;
    if not found and v_deep_time #>> '{payload,interval,previous_record_id}' is not null then
      raise exception 'First DEEPTime coordinate cannot name a predecessor';
    end if;

    insert into public.arcsweep_deep_time_records (
      record_id,
      cycle_id,
      continuity_packet_id,
      review_receipt_id,
      world_id,
      sequence_id,
      lambda,
      observed_at,
      record_fingerprint,
      payload
    ) values (
      v_deep_time ->> 'record_id',
      v_deep_time ->> 'cycle_id',
      v_deep_time ->> 'continuity_packet_id',
      v_deep_time ->> 'review_receipt_id',
      v_deep_time ->> 'world_id',
      v_deep_time ->> 'sequence_id',
      (v_deep_time ->> 'lambda')::bigint,
      (v_deep_time ->> 'observed_at')::timestamptz,
      v_deep_time ->> 'record_fingerprint',
      v_deep_time -> 'payload'
    )
    on conflict (cycle_id) do nothing;

    select * into v_existing_deep_time
    from public.arcsweep_deep_time_records
    where cycle_id = v_cycle_id;
    if v_existing_deep_time.record_id <> v_deep_time ->> 'record_id'
      or v_existing_deep_time.review_receipt_id <> v_deep_time ->> 'review_receipt_id' then
      raise exception 'Observation cycle already has a different DEEPTime record';
    end if;
  end if;

  insert into public.house_runtime_events (
    event_id,
    idempotency_key,
    continuity_packet_id,
    world_id,
    cycle_id,
    event_type,
    actor_id,
    occurred_at,
    packet_id,
    packet_fingerprint,
    source_receipt_ids,
    payload
  ) values (
    v_event ->> 'event_id',
    v_event ->> 'idempotency_key',
    v_event ->> 'continuity_packet_id',
    v_event ->> 'world_id',
    v_event ->> 'cycle_id',
    v_event ->> 'event_type',
    v_event ->> 'actor_id',
    (v_event ->> 'occurred_at')::timestamptz,
    v_event ->> 'packet_id',
    v_event ->> 'packet_fingerprint',
    v_event -> 'source_receipt_ids',
    v_event -> 'payload'
  )
  returning event_sequence into v_event_sequence;

  return jsonb_build_object(
    'applied', true,
    'idempotent', false,
    'event_id', v_event ->> 'event_id',
    'event_sequence', v_event_sequence,
    'continuity_packet_id', v_cycle.continuity_packet_id
  );
end;
$$;

revoke all on function public.house_runtime_apply_observation_command(jsonb) from public, anon, authenticated;
grant execute on function public.house_runtime_apply_observation_command(jsonb) to service_role;

insert into public.observatory_data_sources
  (source_key, table_name, domain, classification, contract_version, default_order, active_filter, metadata)
values
  (
    'house.runtime_events',
    'house_runtime_events',
    'relational-continuity',
    'receipted',
    'hearthgate.runtime-braid-event/v1',
    'event_sequence.desc',
    '{}'::jsonb,
    '{"role":"private append-only Runtime Braid event spine","access":"sealed-house-runtime","transport":"brokered-realtime"}'::jsonb
  )
on conflict (source_key) do update set
  table_name = excluded.table_name,
  domain = excluded.domain,
  classification = excluded.classification,
  contract_version = excluded.contract_version,
  default_order = excluded.default_order,
  active_filter = excluded.active_filter,
  is_live = true,
  metadata = excluded.metadata,
  updated_at = now();

update public.observatory_data_sources
set active_filter = '{}'::jsonb,
    metadata = coalesce(metadata, '{}'::jsonb) || '{"access":"sealed-house-runtime","continuity":"house-runtime-braid/v1"}'::jsonb,
    updated_at = now()
where source_key = 'arcsweep.feedback_cycles';

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'house_runtime_events'
  ) then
    alter publication supabase_realtime add table public.house_runtime_events;
  end if;
end
$$;
