-- Target: Vala Work only (project ref frqrxmshxftpylwdtsdm).
-- Do not apply this migration to the canonical Flameclyffe Supabase project.

create table if not exists public.matrix_stream (
  id bigint generated by default as identity primary key,
  step integer not null,
  raw_coordinates jsonb not null,
  projected_coordinates jsonb not null,
  timestamp double precision not null,
  created_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.matrix_stream enable row level security;

-- ArcSweep/Hearthgate is read-only from the browser.
revoke insert, update, delete on table public.matrix_stream from anon, authenticated;
grant select on table public.matrix_stream to anon, authenticated;
grant select, insert, update, delete on table public.matrix_stream to service_role;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'matrix_stream'
      and policyname = 'Allow public read access to streams'
  ) then
    create policy "Allow public read access to streams"
      on public.matrix_stream
      for select
      to anon, authenticated
      using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'matrix_stream'
  ) then
    alter publication supabase_realtime add table public.matrix_stream;
  end if;
end
$$;
